document.addEventListener('DOMContentLoaded',initAdmin);async function initAdmin(){if(!requireLogin())return;if(!['admin','superuser'].includes(auth.user?.role)){alert('Admin access required');location.href='index.html';return}document.querySelector('.logout-btn')?.addEventListener('click',logout);addRoomManagementUI();await Promise.all([loadStats(),loadBookings(),loadUsers(),loadRoomsAdmin()])}
async function loadStats(){try{const s=await api('/admin/dashboard');document.getElementById('totalBookings').textContent=s.totalBookings;document.getElementById('totalUsers').textContent=s.totalUsers;document.getElementById('totalRevenue').textContent=`$${s.totalRevenue}`}catch(e){alert(e.message)}}
async function loadBookings(){const table=document.getElementById('bookingTable');const bs=await api('/bookings');table.innerHTML='<tr><th>Reference</th><th>Guest</th><th>Room</th><th>Dates</th><th>Total</th><th>Status</th><th>Action</th></tr>'+bs.map(b=>`<tr><td>${b.bookingReference}</td><td>${b.fullName}</td><td>${b.room?.name||'-'}</td><td>${new Date(b.checkIn).toLocaleDateString()} - ${new Date(b.checkOut).toLocaleDateString()}</td><td>$${b.totalAmount}</td><td>${b.status}/${b.paymentStatus}</td><td>${b.status!=='cancelled'?`<button onclick="adminCancel('${b._id}')">Cancel</button>`:''}</td></tr>`).join('')}
async function adminCancel(id){const reason=prompt('Cancellation reason:','Cancelled by admin');if(reason===null)return;try{await api(`/bookings/${id}/cancel`,{method:'PATCH',body:JSON.stringify({reason})});await Promise.all([loadBookings(),loadStats()])}catch(e){alert(e.message)}}
async function loadUsers(){const us=await api('/admin/users'),t=document.getElementById('userTable');t.innerHTML='<tr><th>Name</th><th>Email</th><th>Role</th><th>Joined</th></tr>'+us.map(u=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.role}</td><td>${new Date(u.createdAt).toLocaleDateString()}</td></tr>`).join('')}
function addRoomManagementUI(){const parent=document.querySelector('.admin-container');const box=document.createElement('section');box.className='section-box';box.innerHTML=`<h2>Room Management</h2><form id="roomAdminForm" class="admin-room-form"><input id="rn" placeholder="Room number" required><input id="rname" placeholder="Room name" required><select id="rtype"><option>standard</option><option>deluxe</option><option>suite</option></select><input id="rprice" type="number" min="0" placeholder="Price" required><input id="rcap" type="number" min="1" value="2" placeholder="Capacity"><input id="ramen" placeholder="Amenities comma separated"><button class="btn-primary">Add Room</button></form><div id="roomAdminList"></div>`;parent.appendChild(box);document.getElementById('roomAdminForm').onsubmit=addRoomAdmin}
async function addRoomAdmin(e){e.preventDefault();try{await api('/rooms',{method:'POST',body:JSON.stringify({roomNumber:rn.value,name:rname.value,roomType:rtype.value,price:+rprice.value,capacity:+rcap.value,amenities:ramen.value.split(',').map(x=>x.trim()).filter(Boolean)})});e.target.reset();await loadRoomsAdmin()}catch(err){alert(err.message)}}
async function loadRoomsAdmin(){const list=document.getElementById('roomAdminList');if(!list)return;const rooms=await api('/rooms');list.innerHTML='<table><tr><th>No.</th><th>Name</th><th>Type</th><th>Price</th><th>Status</th><th>Action</th></tr>'+rooms.map(r=>`<tr><td>${r.roomNumber}</td><td>${r.name}</td><td>${r.roomType}</td><td>$${r.price}</td><td>${r.status}</td><td><button onclick="editRoom('${r._id}',${r.price})">Edit price</button> <button onclick="deleteRoom('${r._id}')">Delete</button></td></tr>`).join('')+'</table>'}
async function editRoom(id,old){const price=prompt('New nightly price:',old);if(price===null)return;try{await api(`/rooms/${id}`,{method:'PUT',body:JSON.stringify({price:+price})});await loadRoomsAdmin()}catch(e){alert(e.message)}}async function deleteRoom(id){if(!confirm('Delete this room?'))return;try{await api(`/rooms/${id}`,{method:'DELETE'});await loadRoomsAdmin()}catch(e){alert(e.message)}}
